export const restaurantsAndCafes = [
  {
    id: 1,
    type: 'cafe',
    name: 'Cafe Supreme',
    phoneNumber: '+1234567890',
    address: '123 Main St, Cityville, Country',
    imageLink: require('../../assets/images/restaurants/rest1.jpg'),
  },
  {
    id: 2,
    type: 'restaurant',
    name: 'Pizza Hut',
    phoneNumber: '+9876543210',
    address: '456 Elm St, Townsville, Country',
    imageLink: require('../../assets/images/restaurants/rest2.jpg'),
  },
  {
    id: 3,
    type: 'cafe',
    name: 'Burger Bistro',
    phoneNumber: '+1122334455',
    address: '789 Oak St, Villageland, Country',
    imageLink: require('../../assets/images/restaurants/rest3.jpg'),
  },
  {
    id: 4,
    type: 'restaurant',
    name: 'Pasta Palace',
    phoneNumber: '+9988776655',
    address: '246 Maple St, Hamletown, Country',
    imageLink: require('../../assets/images/restaurants/rest4.jpg'),
  },
  {
    id: 5,
    type: 'restaurant',
    name: 'Sushi Bar',
    phoneNumber: '+5544332211',
    address: '135 Pine St, Cityville, Country',
    imageLink: require('../../assets/images/restaurants/rest5.jpg'),
  },
  {
    id: 6,
    type: 'cafe',
    name: 'Coffee Corner',
    phoneNumber: '+4433221100',
    address: '567 Walnut St, Villageland, Country',
    imageLink: require('../../assets/images/restaurants/rest6.jpg'),
  },
  {
    id: 7,
    type: 'restaurant',
    name: 'Steakhouse Grill',
    phoneNumber: '+1122003344',
    address: '890 Cedar St, Townsville, Country',
    imageLink: require('../../assets/images/restaurants/rest7.jpg'),
  },
  {
    id: 8,
    type: 'cafe',
    name: 'Taco Time',
    phoneNumber: '+9988776655',
    address: '579 Oak St, Hamletown, Country',
    imageLink: require('../../assets/images/restaurants/rest8.jpg'),
  },
  {
    id: 9,
    type: 'restaurant',
    name: 'Ice Cream Paradise',
    phoneNumber: '+5544332211',
    address: '124 Pine St, Cityville, Country',
    imageLink: require('../../assets/images/restaurants/rest9.jpg'),
  },
  {
    id: 10,
    type: 'cafe',
    name: 'Bakery Delights',
    phoneNumber: '+4433221100',
    address: '356 Maple St, Villageland, Country',
    imageLink: require('../../assets/images/restaurants/rest10.jpg'),
  },
];
