export const restaurantsAndCafes = [
  {
    id: 1,
    type: 'cafe',
    name: 'Cafe Supreme',
    phoneNumber: '+1234567890',
    address: '123 Main St, Cityville, Country',
    imageLink: require('../assets/images/restaurants/rest1.jpg'),
    openAt: '19:00',
    closeAt: '18:00',
  },
  {
    id: 2,
    type: 'restaurant',
    name: 'Pizza Hut',
    phoneNumber: '+9876543210',
    address: '456 Elm St, Townsville, Country',
    imageLink: require('../assets/images/restaurants/rest2.jpg'),
    openAt: '11:00',
    closeAt: '16:00',
  },
  {
    id: 3,
    type: 'cafe',
    name: 'Burger Bistro',
    phoneNumber: '+1122334455',
    address: '789 Oak St, Villageland, Country',
    imageLink: require('../assets/images/restaurants/rest3.jpg'),
    openAt: '06:00',
    closeAt: '02:00',
  },
  {
    id: 4,
    type: 'restaurant',
    name: 'Pasta Palace',
    phoneNumber: '+9988776655',
    address: '246 Maple St, Hamletown, Country',
    imageLink: require('../assets/images/restaurants/rest4.jpg'),
    openAt: '05:00',
    closeAt: '01:00',
  },
  {
    id: 5,
    type: 'restaurant',
    name: 'Sushi Bar',
    phoneNumber: '+5544332211',
    address: '135 Pine St, Cityville, Country',
    imageLink: require('../assets/images/restaurants/rest5.jpg'),
    openAt: '06:00',
    closeAt: '22:00',
  },
  {
    id: 6,
    type: 'cafe',
    name: 'Coffee Corner',
    phoneNumber: '+4433221100',
    address: '567 Walnut St, Villageland, Country',
    imageLink: require('../assets/images/restaurants/rest6.jpg'),
    openAt: '22:00',
    closeAt: '19:00',
  },
  {
    id: 7,
    type: 'restaurant',
    name: 'Steakhouse Grill',
    phoneNumber: '+1122003344',
    address: '890 Cedar St, Townsville, Country',
    imageLink: require('../assets/images/restaurants/rest7.jpg'),
    openAt: '03:00',
    closeAt: '11:00',
  },
  {
    id: 8,
    type: 'cafe',
    name: 'Taco Time',
    phoneNumber: '+9988776655',
    address: '579 Oak St, Hamletown, Country',
    imageLink: require('../assets/images/restaurants/rest8.jpg'),
    openAt: '04:00',
    closeAt: '16:00',
  },
  {
    id: 9,
    type: 'restaurant',
    name: 'Ice Cream Paradise',
    phoneNumber: '+5544332211',
    address: '124 Pine St, Cityville, Country',
    imageLink: require('../assets/images/restaurants/rest9.jpg'),
    openAt: '05:00',
    closeAt: '05:00',
  },
  {
    id: 10,
    type: 'cafe',
    name: 'Bakery Delights',
    phoneNumber: '+4433221100',
    address: '356 Maple St, Villageland, Country',
    imageLink: require('../assets/images/restaurants/rest10.jpg'),
    openAt: '20:00',
    closeAt: '15:00',
  },
  {
    id: 11,
    type: 'cafe',
    name: 'Cafe Supreme',
    phoneNumber: '+1234567890',
    address: '123 Main St, Cityville, Country',
    imageLink: require('../assets/images/restaurants/rest1.jpg'),
    openAt: '19:00',
    closeAt: '18:00',
  },
  {
    id: 12,
    type: 'restaurant',
    name: 'Pizza Hut',
    phoneNumber: '+9876543210',
    address: '456 Elm St, Townsville, Country',
    imageLink: require('../assets/images/restaurants/rest2.jpg'),
    openAt: '11:00',
    closeAt: '16:00',
  },
  {
    id: 13,
    type: 'cafe',
    name: 'Burger Bistro',
    phoneNumber: '+1122334455',
    address: '789 Oak St, Villageland, Country',
    imageLink: require('../assets/images/restaurants/rest3.jpg'),
    openAt: '06:00',
    closeAt: '02:00',
  },
  {
    id: 14,
    type: 'restaurant',
    name: 'Pasta Palace',
    phoneNumber: '+9988776655',
    address: '246 Maple St, Hamletown, Country',
    imageLink: require('../assets/images/restaurants/rest4.jpg'),
    openAt: '05:00',
    closeAt: '01:00',
  },
  {
    id: 15,
    type: 'restaurant',
    name: 'Sushi Bar',
    phoneNumber: '+5544332211',
    address: '135 Pine St, Cityville, Country',
    imageLink: require('../assets/images/restaurants/rest5.jpg'),
    openAt: '06:00',
    closeAt: '22:00',
  },
  {
    id: 16,
    type: 'cafe',
    name: 'Coffee Corner',
    phoneNumber: '+4433221100',
    address: '567 Walnut St, Villageland, Country',
    imageLink: require('../assets/images/restaurants/rest6.jpg'),
    openAt: '22:00',
    closeAt: '19:00',
  },
  {
    id: 17,
    type: 'restaurant',
    name: 'Steakhouse Grill',
    phoneNumber: '+1122003344',
    address: '890 Cedar St, Townsville, Country',
    imageLink: require('../assets/images/restaurants/rest7.jpg'),
    openAt: '03:00',
    closeAt: '11:00',
  },
  {
    id: 18,
    type: 'cafe',
    name: 'Taco Time',
    phoneNumber: '+9988776655',
    address: '579 Oak St, Hamletown, Country',
    imageLink: require('../assets/images/restaurants/rest8.jpg'),
    openAt: '04:00',
    closeAt: '16:00',
  },
  {
    id: 19,
    type: 'restaurant',
    name: 'Ice Cream Paradise',
    phoneNumber: '+5544332211',
    address: '124 Pine St, Cityville, Country',
    imageLink: require('../assets/images/restaurants/rest9.jpg'),
    openAt: '05:00',
    closeAt: '05:00',
  },
  {
    id: 20,
    type: 'cafe',
    name: 'Bakery Delights',
    phoneNumber: '+4433221100',
    address: '356 Maple St, Villageland, Country',
    imageLink: require('../assets/images/restaurants/rest10.jpg'),
    openAt: '20:00',
    closeAt: '15:00',
  },
];
