export {default as WelcomeScreen} from './WelcomeScreen/WelcomeScreen';
export {default as AuthScreen} from './AuthScreen/AuthScreen';
export {default as HomeScreen} from './HomeScreen/HomeScreen';
export {default as DeliveryScreen} from './DeliveryScreen/DeliveryScreen';
export {default as ReserveTable} from './ReserveTable/ReserveTable';
export {default as Reservations} from './ReserveTable/ReserveTable';
export {default as StoreScreen} from './StoreScreen/StoreScreen';
export {default as Profile} from './Profile/Profile';
export {default as Discover} from './Discover/Discover';
