export const Images = {
  noResult: require('./images/noResult.png'),
  camp1: require('./images/camp1.png'),
  camp2: require('./images/camp2.png'),
  camp3: require('./images/camp3.png'),
  camp4: require('./images/camp4.png'),
  timeTable: require('./images/timeTable.png'),
  table: require('./images/table.png'),
  store: require('./images/store.png'),
  delivery: require('./images/delivery.png'),
  userCard: require('./images/userCard.png'),
  profileIcon: require('./images/profileIcon.png'),
  barcode: require('./images/barcode.png'),
  support: require('./images/support.png'),
  food1: require('./images/food1.jpg'),
  food2: require('./images/food2.jpg'),
  food3: require('./images/food3.jpg'),
  icons: {
    backButton: require('./icons/backBtn.png'),
    expand: require('./icons/expand.png'),
    compress: require('./icons/compress.png'),
    userIcon: require('./icons/userIcon.png'),
    searchIcon: require('./icons/SearchIcon.png'),
    storeItem: require('./icons/storeItem.png'),
    arrowRightBlack: require('./icons/arrowRightBlack.png'),

    unLikedImg: require('./icons/loveFaded.png'),
    likeImg: require('./icons/love.png'),
    phoneIcon: require('./icons/phone.png'),
    addressIcon: require('./icons/address.png'),
  },
  products: {
    arabica: require('./images/products/arabica.png'),
    burger: require('./images/products/burger.png'),
    capuccino: require('./images/products/capuccino.png'),
    latte: require('./images/products/latte.png'),
    pizza: require('./images/products/pizza.png'),
    PureBlack: require('./images/products/PureBlack.png'),
    rebusta: require('./images/products/rebusta.png'),
    namkeen: require('./images/products/namkeen.png'),
    samosa: require('./images/products/samosa.png'),
    danish: require('./images/products/Danish.jpg'),
    truffle: require('./images/products/TrufflePastries.jpg'),
    tea: require('./images/products/tea.jpg'),
    greenTea: require('./images/products/greanTea.jpg'),
  },
};
